### PR TITLE
Game Added

### PR DESCRIPTION
**Pull request by ad1tya24**
Rock paper scissor added

Aditya A S
PES2UG21CS033

### CODE REVIEW

**Review by mukunddeepak — APPROVED** [review]
Works!

**Comment by mukunddeepak** [comment]
!bounty 20

**Comment by ad1tya24** [comment]
@mukunddeepak  a little more points would help :) (says 70)

**Comment by mukunddeepak** [comment]
This was the second game and the points do significantly decrease for that.
I feel like what you received is fair!

**Pull request merged**
