### PR TITLE
Added QR code functionality, extra modules needed have been specified in requirments.txt.

### PR DESCRIPTION
**Pull request by surajkadapa**

### CODE REVIEW

**Comment by mukunddeepak** [comment]
@surajkadapa there is an runtime error when i put the UPI option saying no module called png

**Comment by mukunddeepak** [comment]
image

**Comment by surajkadapa** [comment]
image
There is no module called png which I am importing, and I have got the QR code in my machine
image

**Comment by surajkadapa** [comment]
@mukunddeepak

**Comment by mukunddeepak** [comment]
Still getting that error on 2 other systems. MacOS and Linux. Find an alternative in next 15 mins please! Or this issue will be reassigned.

**Comment by surajkadapa** [comment]
It is working on MacOS and Linux now, couldn't update it before due to freeze.

**Comment by mukunddeepak** [comment]
Ok lemme review

**Comment by surajkadapa** [comment]
@mukunddeepak you have to install all the modules specified in the requirements.txt.

**Comment by mukunddeepak** [comment]
YES IT WORKS HALLELUJIAH!

**Comment by surajkadapa** [comment]
YAYYYYY

**Review by mukunddeepak — APPROVED** [review]

**Comment by mukunddeepak** [comment]
!bounty 35

**Pull request merged**
