### PR TITLE
Added New Game

### PR DESCRIPTION
**Pull request by nik2203**
#34 Add a new game to the list
PES2UG21CS334
Nikhil Girish

### CODE REVIEW

**Review by mukunddeepak — APPROVED** [review]

**Comment by mukunddeepak** [comment]
It works!

**Comment by mukunddeepak** [comment]
QR Code Generation points will not be given.

**Comment by mukunddeepak** [comment]
!bounty 62

**Comment by NavinShrinivas** [comment]
!bounty 40

**Pull request merged**
